manifest-version = 1

[component]
name = "Segment"
version = "1.1.0"
category = "data-collection"
subcategory = "analytics"
description = """
# Segment Component

[https://www.edgee.cloud/edgee/segment](https://www.edgee.cloud/edgee/segment)

## Overview

The **Segment** component by Edgee enables seamless integration of Segment's customer data platform (CDP) into your Edgee projects.
This component allows you to collect, clean, and activate your customer data directly at the edge, eliminating the need to embed Segment’s script on your website—thereby improving site performance and adhering to strict privacy standards.

---

## Key Features & Benefits

### Features

- **Edge Deployment**: Deploys analytics at the edge, reducing latency and improving performance.
- **Privacy-Focused**: Operates before the page loads, ensuring compliance with privacy regulations.
- **Real-Time Data Processing**: Processes data in real-time, enabling immediate insights.
- **Easy Integration**: Simplifies the integration of Segment into your existing Edgee projects.

### Benefits

- **Faster Load Times**: Enhanced user experience by avoiding client-side SDKs.
- **Regulation Compliance**: Streamlined adherence to GDPR, CCPA, and other privacy rules.
- **Real-Time Insights**: Actionable data available instantly.
- **Lower Overhead**: Reduces reliance on third-party scripts and complex configurations.

---

## Use Cases

- **Privacy-Compliant Analytics**: Collect and analyze user data without compromising privacy.
- **Performance Optimization**: Improve page speed by offloading analytics to the edge.
- **Open-Source Preference**: Use a customizable, open CDP with full control.
- **Simplified Integration**: Easy to set up within Edgee without external JS or SDKs.

---

Additional resources: [Segment Documentation](https://segment.com/docs)
"""
documentation = "https://www.edgee.cloud/docs/components/data-collection/segment"
repository = "https://github.com/edgee-cloud/segment-component"
wit-version = "1.0.0"
icon-path = "segment.png"
language = "Rust"

[component.build]
command = "cargo build --target wasm32-wasip2 --release && rm -f segment.wasm && cp ./target/wasm32-wasip2/release/segment_component.wasm segment.wasm"
output_path = "segment.wasm"

[component.settings.segment_project_id]
title = "Project ID"
type = "string"
required = true
description = """
The project ID for your Segment project"""

[component.settings.segment_write_key]
title = "Write Key"
type = "string"
required = true
secret = true
description = """
The write key for your Segment project"""

